//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Abonné
{
    public Abonné()
    {
        this.Achat = new HashSet<Achat>();
    }

    public int Code_Abonné { get; set; }
    public string Nom_Abonné { get; set; }
    public string Prénom_Abonné { get; set; }
    public string Login { get; set; }
    public string Password { get; set; }
    public string Adresse { get; set; }
    public string Ville { get; set; }
    public string Code_Postal { get; set; }
    public Nullable<int> Code_Pays { get; set; }
    public string Email { get; set; }
    public string UserId { get; set; }
    public Nullable<int> Credit { get; set; }

    public virtual Pays Pays { get; set; }
    public virtual ICollection<Achat> Achat { get; set; }
}

public partial class Achat
{
    public int Code_Achat { get; set; }
    public int Code_Enregistrement { get; set; }
    public int Code_Abonné { get; set; }

    public virtual Abonné Abonné { get; set; }
    public virtual Enregistrement Enregistrement { get; set; }
}

public partial class Album
{
    public Album()
    {
        this.Disque = new HashSet<Disque>();
    }

    public int Code_Album { get; set; }
    public string Titre_Album { get; set; }
    public Nullable<int> Année_Album { get; set; }
    public Nullable<int> Code_Genre { get; set; }
    public Nullable<int> Code_Editeur { get; set; }
    public byte[] Pochette { get; set; }
    public string ASIN { get; set; }

    public virtual Editeur Editeur { get; set; }
    public virtual Genre Genre { get; set; }
    public virtual ICollection<Disque> Disque { get; set; }
}

public partial class Composer
{
    public int Code_Composer { get; set; }
    public Nullable<int> Code_Musicien { get; set; }
    public Nullable<int> Code_Oeuvre { get; set; }

    public virtual Musicien Musicien { get; set; }
    public virtual Oeuvre Oeuvre { get; set; }
}

public partial class Composition
{
    public Composition()
    {
        this.Composition_Oeuvre = new HashSet<Composition_Oeuvre>();
        this.Enregistrement = new HashSet<Enregistrement>();
    }

    public int Code_Composition { get; set; }
    public string Titre_Composition { get; set; }
    public Nullable<int> Année { get; set; }
    public string Composante_Composition { get; set; }

    public virtual ICollection<Composition_Oeuvre> Composition_Oeuvre { get; set; }
    public virtual ICollection<Enregistrement> Enregistrement { get; set; }
}

public partial class Composition_Disque
{
    public int Code_Contenir { get; set; }
    public Nullable<int> Code_Disque { get; set; }
    public Nullable<int> Code_Morceau { get; set; }
    public Nullable<int> Position { get; set; }

    public virtual Disque Disque { get; set; }
    public virtual Enregistrement Enregistrement { get; set; }
}

public partial class Composition_Oeuvre
{
    public int Code_Composer_Oeuvre { get; set; }
    public Nullable<int> Code_Oeuvre { get; set; }
    public Nullable<int> Code_Composition { get; set; }

    public virtual Composition Composition { get; set; }
    public virtual Oeuvre Oeuvre { get; set; }
}

public partial class Direction
{
    public int Code_Direction { get; set; }
    public Nullable<int> Code_Musicien { get; set; }
    public Nullable<int> Code_Morceau { get; set; }
    public Nullable<int> Code_Orchestre { get; set; }

    public virtual Enregistrement Enregistrement { get; set; }
    public virtual Musicien Musicien { get; set; }
    public virtual Orchestres Orchestres { get; set; }
}

public partial class Disque
{
    public Disque()
    {
        this.Composition_Disque = new HashSet<Composition_Disque>();
    }

    public int Code_Disque { get; set; }
    public int Code_Album { get; set; }
    public string Référence_Album { get; set; }
    public string Référence_Disque { get; set; }

    public virtual Album Album { get; set; }
    public virtual ICollection<Composition_Disque> Composition_Disque { get; set; }
}

public partial class Editeur
{
    public Editeur()
    {
        this.Album = new HashSet<Album>();
    }

    public int Code_Editeur { get; set; }
    public string Nom_Editeur { get; set; }
    public Nullable<int> Code_Pays { get; set; }

    public virtual ICollection<Album> Album { get; set; }
    public virtual Pays Pays { get; set; }
}

public partial class Enregistrement
{
    public Enregistrement()
    {
        this.Achat = new HashSet<Achat>();
        this.Composition_Disque = new HashSet<Composition_Disque>();
        this.Direction = new HashSet<Direction>();
        this.Interpréter = new HashSet<Interpréter>();
    }

    public int Code_Morceau { get; set; }
    public string Titre { get; set; }
    public int Code_Composition { get; set; }
    public string Nom_de_Fichier { get; set; }
    public string Durée { get; set; }
    public Nullable<int> Durée_Seconde { get; set; }
    public Nullable<decimal> Prix { get; set; }
    public byte[] Extrait { get; set; }

    public virtual ICollection<Achat> Achat { get; set; }
    public virtual Composition Composition { get; set; }
    public virtual ICollection<Composition_Disque> Composition_Disque { get; set; }
    public virtual ICollection<Direction> Direction { get; set; }
    public virtual ICollection<Interpréter> Interpréter { get; set; }
}

public partial class Genre
{
    public Genre()
    {
        this.Album = new HashSet<Album>();
        this.Musicien = new HashSet<Musicien>();
    }

    public int Code_Genre { get; set; }
    public string Libellé_Abrégé { get; set; }

    public virtual ICollection<Album> Album { get; set; }
    public virtual ICollection<Musicien> Musicien { get; set; }
}

public partial class Instrument
{
    public Instrument()
    {
        this.Instrumentation = new HashSet<Instrumentation>();
        this.Interpréter = new HashSet<Interpréter>();
        this.Musicien = new HashSet<Musicien>();
    }

    public int Code_Instrument { get; set; }
    public string Nom_Instrument { get; set; }
    public byte[] Image { get; set; }

    public virtual ICollection<Instrumentation> Instrumentation { get; set; }
    public virtual ICollection<Interpréter> Interpréter { get; set; }
    public virtual ICollection<Musicien> Musicien { get; set; }
}

public partial class Instrumentation
{
    public int Code_Instrumentation { get; set; }
    public Nullable<int> Code_Oeuvre { get; set; }
    public Nullable<int> Code_Instrument { get; set; }

    public virtual Instrument Instrument { get; set; }
    public virtual Oeuvre Oeuvre { get; set; }
}

public partial class Interpréter
{
    public int Code_Interpréter { get; set; }
    public Nullable<int> Code_Morceau { get; set; }
    public Nullable<int> Code_Musicien { get; set; }
    public Nullable<int> Code_Instrument { get; set; }

    public virtual Enregistrement Enregistrement { get; set; }
    public virtual Instrument Instrument { get; set; }
    public virtual Musicien Musicien { get; set; }
}

public partial class Musicien
{
    public Musicien()
    {
        this.Composer = new HashSet<Composer>();
        this.Direction = new HashSet<Direction>();
        this.Interpréter = new HashSet<Interpréter>();
    }

    public int Code_Musicien { get; set; }
    public string Nom_Musicien { get; set; }
    public string Prénom_Musicien { get; set; }
    public Nullable<int> Année_Naissance { get; set; }
    public Nullable<int> Année_Mort { get; set; }
    public Nullable<int> Code_Pays { get; set; }
    public Nullable<int> Code_Genre { get; set; }
    public Nullable<int> Code_Instrument { get; set; }
    public byte[] Photo { get; set; }

    public virtual ICollection<Composer> Composer { get; set; }
    public virtual ICollection<Direction> Direction { get; set; }
    public virtual Genre Genre { get; set; }
    public virtual Instrument Instrument { get; set; }
    public virtual ICollection<Interpréter> Interpréter { get; set; }
    public virtual Pays Pays { get; set; }
}

public partial class Oeuvre
{
    public Oeuvre()
    {
        this.Composer = new HashSet<Composer>();
        this.Composition_Oeuvre = new HashSet<Composition_Oeuvre>();
        this.Instrumentation = new HashSet<Instrumentation>();
    }

    public int Code_Oeuvre { get; set; }
    public string Titre_Oeuvre { get; set; }
    public string Sous_Titre { get; set; }
    public string Tonalité { get; set; }
    public Nullable<int> Code_Type { get; set; }
    public Nullable<int> Année { get; set; }
    public string Opus { get; set; }
    public Nullable<int> Numéro_Opus { get; set; }

    public virtual ICollection<Composer> Composer { get; set; }
    public virtual ICollection<Composition_Oeuvre> Composition_Oeuvre { get; set; }
    public virtual ICollection<Instrumentation> Instrumentation { get; set; }
    public virtual Type_Morceaux Type_Morceaux { get; set; }
}

public partial class Orchestres
{
    public Orchestres()
    {
        this.Direction = new HashSet<Direction>();
    }

    public int Code_Orchestre { get; set; }
    public string Nom_Orchestre { get; set; }

    public virtual ICollection<Direction> Direction { get; set; }
}

public partial class Pays
{
    public Pays()
    {
        this.Abonné = new HashSet<Abonné>();
        this.Editeur = new HashSet<Editeur>();
        this.Musicien = new HashSet<Musicien>();
    }

    public int Code_Pays { get; set; }
    public string Nom_Pays { get; set; }

    public virtual ICollection<Abonné> Abonné { get; set; }
    public virtual ICollection<Editeur> Editeur { get; set; }
    public virtual ICollection<Musicien> Musicien { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Type_Morceaux
{
    public Type_Morceaux()
    {
        this.Oeuvre = new HashSet<Oeuvre>();
    }

    public int Code_Type { get; set; }
    public string Libellé_Type { get; set; }
    public string Description { get; set; }

    public virtual ICollection<Oeuvre> Oeuvre { get; set; }
}
