//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Classique_Web_Entities : DbContext
{
    public Classique_Web_Entities()
        : base("name=Classique_Web_Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Abonné> Abonné { get; set; }
    public DbSet<Achat> Achat { get; set; }
    public DbSet<Album> Album { get; set; }
    public DbSet<Composer> Composer { get; set; }
    public DbSet<Composition> Composition { get; set; }
    public DbSet<Composition_Disque> Composition_Disque { get; set; }
    public DbSet<Composition_Oeuvre> Composition_Oeuvre { get; set; }
    public DbSet<Direction> Direction { get; set; }
    public DbSet<Disque> Disque { get; set; }
    public DbSet<Editeur> Editeur { get; set; }
    public DbSet<Enregistrement> Enregistrement { get; set; }
    public DbSet<Genre> Genre { get; set; }
    public DbSet<Instrument> Instrument { get; set; }
    public DbSet<Instrumentation> Instrumentation { get; set; }
    public DbSet<Interpréter> Interpréter { get; set; }
    public DbSet<Musicien> Musicien { get; set; }
    public DbSet<Oeuvre> Oeuvre { get; set; }
    public DbSet<Orchestres> Orchestres { get; set; }
    public DbSet<Pays> Pays { get; set; }
    public DbSet<sysdiagrams> sysdiagrams { get; set; }
    public DbSet<Type_Morceaux> Type_Morceaux { get; set; }
}
